baseURL = 'https://uri-nyx.art/'
languageCode = 'en-us'
title = 'Uri Nyx'
theme = 'even'

[taxonomies]
    category = 'categories'
    project = 'projects'

[Params]
    mupes  = '/categories/education'
    github = 'https://github.com/uri-nyx'
    email = 'mailto:rserranof03@usal.es'
    dateFormat = '2 January 2006'
    background = '/images/background.png'

[menu]
    [[menu.main]]
    name = 'projects'
    pre = 'projects'
    url = '/projects/'
    weight = 1
    [[menu.main]]
    name = 'about'
    pre = 'about'
    url = '/about/#portrait'
    weight = 2
    [[menu.main]]
    name = 'education'
    pre = 'education'
    url = '/projects/innovacion'
    weight = 3

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2